services:
  order-service-db:
    image: postgres:18-alpine
    container_name: order_service_postgres
    environment:
      - POSTGRES_DB=${ORDER_SERVICE_DB_NAME}
      - POSTGRES_USER=${ORDER_SERVICE_DB_USERNAME}
      - POSTGRES_PASSWORD=${ORDER_SERVICE_DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${ORDER_SERVICE_DB_PORT}:5432"
    volumes:
      - order_service_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  payment-system-order-service:
    image: ghcr.io/yuryshakhau1/payment-system-order-service:latest
    container_name: payment_system_order_service
    profiles:
      - docker
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    environment:
      - ORDER_SERVICE_PORT=${ORDER_SERVICE_PORT}
      - ORDER_SERVICE_DB_NAME=${ORDER_SERVICE_DB_NAME}
      - ORDER_SERVICE_DB_USERNAME=${ORDER_SERVICE_DB_USERNAME}
      - ORDER_SERVICE_DB_PASSWORD=${ORDER_SERVICE_DB_PASSWORD}
      - ORDER_SERVICE_DB_PORT=${ORDER_SERVICE_DB_PORT}
      - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL}
    depends_on:
      - product-service-db

volumes:
  order_service_postgres_data:
