spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: none
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
    enabled: true

  config:
    import: optional:file:../.env[.properties]

crypto:
  card-secret-key: ${CARD_SECRET_KEY}

app:
  product-service-url: ${PRODUCT_SERVICE_URL}